mrs_uav_managers:

  estimation_manager:

    # loaded state estimator plugins
    state_estimators: [
      "rtk",
      "gps_baro",
      "ground_truth",
    ]

    initial_state_estimator: "rtk" # will be used as the first state estimator
    agl_height_estimator: "garmin_agl" # only slightly filtered height for checking min height (not used in control feedback)

  uav_manager:

    takeoff:

      takeoff_height: 2.0

    min_height_checking:
      enabled: false

    max_height_checking:
      enabled: false

  constraint_manager:
    # list of allowed constraints per odometry mode
    allowed_constraints:
      rtk: ["slow", "medium", "fast"]
      gps_baro: ["slow", "medium"]
      ground_truth: ["slow", "medium", "fast"]
      other: ["slow"]

    # those constraints will be used automatically when a localization mode switches
    # and the current constraints are not in the allowed list (next paragraphs)
    default_constraints:
      rtk: "fast" # slow, medium, fast
      gps_baro: "medium"
      ground_truth: "medium"

mrs_uav_trackers:

  mpc_tracker:

    wiggle:
      enabled: true
      amplitude: 2.0 # [m]
      frequency: 0.1 # [Hz]

    # mrs collision avoidance
    collision_avoidance:

      enabled:           true # disabling this will stop this UAV to react to others, but it will still transmit data to others
      enabled_passively: true # disabling this will stop this uav to even transmit its data to others (only if enabled: false)
      radius: 0.25 # [m]
      correction: 3.0 # [m]
