mrs_uav_managers:

  estimation_manager:

    # loaded state estimator plugins
    state_estimators: [
      "rtk",
      "gps_baro",
      "ground_truth",
    ]

    initial_state_estimator: "rtk" # will be used as the first state estimator
    agl_height_estimator: "garmin_agl" # only slightly filtered height for checking min height (not used in control feedback)

  control_manager:

    LeaderFollowerController:
      address: "leader_follower_controller_plugin/LeaderFollowerController"
      namespace: "leader_follower_controller"
      eland_threshold: 20.0 # [m], position error triggering eland
      failsafe_threshold: 30.0 # [m], position error triggering failsafe land
      odometry_innovation_threshold: 1.5 # [m], position odometry innovation threshold
      human_switchable: true
      # multiple followers
      offset:
        x: 5.0
        y: 5.0
        z: 0.0 # [m], offset from the leader position
      follower_name: "uav1" # name of the follower UAV, used for multiple followers
      # which outputs the controller can provide
      outputs:
        actuators:             false
        control_group:         false
        attitude_rate:         false
        attitude:              true
        acceleration_hdg_rate: false
        acceleration_hdg:      false
        velocity_hdg_rate:     false
        velocity_hdg:          false
        position:              false

    # list of names of dynamically loaded controllers
    controllers : [
      "LeaderFollowerController",
    ]

  uav_manager:

    takeoff:
      after_takeoff:
        controller: "LeaderFollowerController"

      takeoff_height: 2.0

    midair_activation:
      after_activation:
        controller: "LeaderFollowerController"

    min_height_checking:
      enabled: false

    max_height_checking:
      enabled: false

mrs_uav_trackers:

  mpc_tracker:

    wiggle:
      enabled: false
      amplitude: 0.5 # [m]
      frequency: 0.2 # [Hz]

    # mrs collision avoidance
    collision_avoidance:

      enabled:           true # disabling this will stop this UAV to react to others, but it will still transmit data to others
      enabled_passively: true # disabling this will stop this uav to even transmit its data to others (only if enabled: false)
      radius: 0.25 # [m]
      correction: 3.0 # [m]
